### ISSUE TITLE
Vector Tiles

### ISSUE THREAD

**Issue by lincomatic** [develar/mapsforge-tile-server#3]
I noticed your code has support for vector tiles, but I can't seem to find any documentation on their format. What client are they for?

**Comment by develar** [comment]
@lincomatic Custom binary format, see https://github.com/develar/route-planner

Rendered on client using pixi.js. Basically it works, but the work is not yet finished (and I am not going to finish it in the near future).

**Comment by lincomatic** [comment]
OK, thanks
